name: Docker Build and Push
inputs:
  context:
    description: context of Dockerfile
  file:
    description: filepath of Dockerfile
    default: Dockerfile
  push:
    description: whether docker image should be pushed
    default: false
  gh-token:
    description: GitHub token for ghcr.io

runs:
  using: "composite"
  steps:
  - id: version
    run: echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
    shell: bash

  - uses: docker/setup-buildx-action@v3

  - uses: docker/login-action@v3
    if: ${{ inputs.push == 'true' }}
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ inputs.gh-token }}

  - uses: docker/build-push-action@v6
    with:
      context: ${{ inputs.context }}
      push: ${{ inputs.push == 'true' }}
      tags: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
      file: ${{ inputs.file }}
